### ISSUE TITLE
set up automated jobs for updating documentation?

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/collaborative_workflow#29] opened 2022-01-12 14:59 UTC
Just a thought that automating documentation updates could be helpful so that it is always in date. https://noaa-fims.github.io/collaborative_workflow/documentation-template.html#step-by-step-documentation-update-process

[ghactions4r](https://github.com/nmfs-fish-tools/ghactions4r#how-do-i-use-these-workflows-in-my-r-package) includes reusable workflows to update documentation and (if desired) code style for R code. I imagine automating the c++ code is also possible.

**Comment by ChristineStawitz-NOAA** [comment] 2022-01-24 18:26
duplicate of https://github.com/NOAA-FIMS/FIMS-planning/issues/27

**Closed by ChristineStawitz-NOAA** 2022-01-24 18:26 UTC
Labels: topic: documentation, type: enhancement
