### ISSUE TITLE
linter(s)

### ISSUE THREAD

**Issue by kristanblackhart-NOAA** [NOAA-FIMS/collaborative_workflow#22] opened 2022-01-11 19:21 UTC
I recommend we adopt a linter - any suggestions @cmlegault @ChristineStawitz-NOAA @k-doering-NOAA @msupernaw?

**Comment by ChristineStawitz-NOAA** [comment] 2022-01-11 19:32
I used the one built into VS code.

**Comment by kristanblackhart-NOAA** [comment] 2022-01-11 21:56
Currently I've just stated "lint your code" without any further recommendations about specific tools, which feels overly prescriptive. Let me know if anyone feels otherwise.

**Comment by kellijohnson-NOAA** [comment] 2022-01-11 22:09
I suggest that a linter be used on the pushed code. Personal linting without directions will lead to inconsistent styling which is harder to read than code that is consistent. The trouble is that everyone has their own preferences, which are all fine, no one is choice is "better" but consistency matters.

**Comment by kristanblackhart-NOAA** [comment] 2022-01-11 22:19
Thanks @kellijohnson-NOAA, that's a really good point about consistency. However, using linting prior to a PR could help to enforce consistent styling and efficient reviews. That's where I was headed with suggesting a team linting tool, but I'm worried about being overly prescriptive with all this...

**Comment by kellijohnson-NOAA** [comment] 2022-01-11 23:23
I have seen the linting happen before or after a pull request is merged in and there are different benefits to either option. I think that outside collaborators enjoy linting and contribute more when formatting happens afterwards so that they don't have to think about it :) But, people can learn more from the automated formatting when they are made aware prior to a pull request being accepted. No "right" answer here.

**Comment by k-doering-NOAA** [comment] 2022-01-12 21:39
I think we can be specific about using one tool.

Btw, I found this github action that can lint for you: https://github.com/shenxianpeng/cpp-linter-action
I'm not sure, though if it fixes the problems for you, or if you have to do it yourself. Would be nice to have something that just fixes the issues, I think.

**Comment by msupernaw** [comment] 2022-01-24 18:29
I really like clang-tidy. It also comes as a plugin for VS code.

https://clang.llvm.org/extra/clang-tidy/

**Comment by ChristineStawitz-NOAA** [comment] 2022-01-25 18:57
duplicate of https://github.com/NOAA-FIMS/FIMS-planning/issues/27

**Closed by ChristineStawitz-NOAA** 2022-01-25 18:57 UTC
Labels: type: duplicate
