### ISSUE TITLE
Add roles/responsibilities section to dev guide?

### ISSUE THREAD

**Issue by kristanblackhart-NOAA** [NOAA-FIMS/collaborative_workflow#20] opened 2022-01-11 19:04 UTC
@ChristineStawitz-NOAA Would it be useful to add a chapter to the contributors guide outlining roles? Some of this info is in the FIMS TOR, so we could reference that but also elaborate (e.g. use the NMT Testing Engineer as consultant on building your tests).

**Comment by kristanblackhart-NOAA** [comment] 2022-01-11 23:04
This chapter could more appropriately be labeled 'governance' and I'm leaning towards it being a good inclusion.

**Comment by ChristineStawitz-NOAA** [comment] 2022-01-25 19:07
duplicate of https://github.com/NOAA-FIMS/collaborative_workflow/issues/36

**Closed by ChristineStawitz-NOAA** 2022-01-25 19:07 UTC
Labels: type: duplicate
