### ISSUE TITLE
Document how to create a reproducible example

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/collaborative_workflow#136] opened 2024-05-21 17:49 UTC
**Is your feature request related to a problem? Please describe.**
To solve problems, we need reproducible examples from the user having the issue. 

**Describe the solution you'd like**
Document in the collaborative workflow how to create a reproducible example.

**Describe alternatives you've considered**
We could also consider asking for a reproducible example in issue templates

**Comment by ChristineStawitz-NOAA** [comment] 2024-05-29 16:30
Making this another/updated issue template would help with debugging some of the case study issues.

**Comment by Bai-Li-NOAA** [comment] 2024-06-13 19:57
I like the idea of including a request for a reproducible example in our issue templates. There are two potential approaches to preparing a reproducible example:

- In the issue template, we can add a link to {[reprex](https://reprex.tidyverse.org/)}, inviting folks to prepare reproducible examples for posting to GitHub issues. However, I haven't used {reprex} before.
- Folks can work with me to create a failed test, if possible, to demonstrate the issue through GitHub Actions if possible. Developers would then only need to fix the R test to resolve the problem.

**Comment by kellijohnson-NOAA** [comment] 2024-06-13 20:23
I think that just the first bullet is sufficient. {sdmTMB} has lots of examples of using {reprex} in their issues. The big thing is that users are going to have to use `data_mile1` in there example because it is data that is accessible to both them and us and allows the code to be executed on different machines without passing files.

I think as a first stab and to close this issue we can provide suggestions to create a reproducible example and point them to the demo vignette and suggest that they augment the code in the vignette to reproduce their error and share it in the issue along with the error.

**Closed** 2024-06-18 03:01 UTC
